id: dk.ehmi.eas
canonical: http://medcomehmi.dk/ig/eas
name: EHMI EAS IG
title: "EHMI Addressing Service (EAS)"
description: The EHMI Addressing Service (EAS)
status: active # draft | active | retired | unknown
version: 2.0.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2025+
releaseLabel: release # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
publisher:
  name: MedCom
  url: https://www.medcom.dk

dependencies:
  hl7.fhir.dk.core: 3.3.0
  medcom.fhir.dk.core: 2.4.0
  medcom.fhir.dk.terminology: 1.8.1
  dk.ehmi.terminology: current
  dk.ehmi.eer: current

parameters:
  apply-contact: true
  apply-publisher: true

menu:
  Home: index.html
  Use cases:
    Use case 1 - Get General Practitioner for a Patient by PatientId: Use-case-1.html
    Use case 2 - Get General Practitioner for a Patient by GPId: Use-case-2.html
    Use case 3 - Get possible General Practitioner for a Patient by PostalCodes: Use-case-3.html
    Use case 4 - Get ReceivingOrganization by SORID: Use-case-4.html
  Profiles: profiles.html
  Security: 
    Security-en: security-english.html
    Security-da: security-danish.html
  Artifacts: artifacts.html
  More:
    Table of Contents: toc.html
    Downloads: downloads.html
    Dependencies: dependencies.html

instanceOptions:
  manualSliceOrdering: true
